

const Inventario = () => {
  return (
    <>
    <div>Inventario</div>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab sapiente et at maxime animi dignissimos voluptate, vel libero optio aperiam laudantium deserunt aspernatur odio eius cupiditate nisi! Atque, eius molestias!
    Sunt, facere? Sapiente dignissimos, vero in natus aut dolorem molestiae nulla veniam doloremque fuga mollitia beatae, rerum necessitatibus distinctio assumenda iusto. Omnis atque fugiat eos repudiandae molestiae, porro harum earum.
    Nobis, accusantium dolorem. Quas soluta recusandae, distinctio maxime neque, possimus nostrum sit error nobis nulla molestias cumque eaque inventore quo praesentium animi natus? Nemo voluptate animi sequi ipsam quisquam magni.
    Laudantium itaque repellat delectus voluptatem a dicta ratione quo accusantium neque quia totam, aspernatur est? Accusantium quae ab cumque distinctio, repellendus velit iure eius ad deserunt dolorem sit aliquam porro.
    Voluptate voluptates debitis nisi, similique corrupti distinctio ea velit explicabo quae quisquam! Et officiis incidunt suscipit assumenda quasi vero aliquam esse, ullam saepe cumque nisi voluptatibus. Architecto beatae fuga quasi.
    Explicabo voluptatem quia porro rerum itaque repudiandae nostrum obcaecati. Labore corrupti dolore vitae. Libero incidunt veritatis consequatur omnis aut. Rem quidem dolorum nam quibusdam ab exercitationem nesciunt vitae possimus dolores.
    Id, rerum pariatur nulla repellat aspernatur ipsa fugit sed adipisci? Magnam esse repellendus possimus nihil deleniti tempore, totam quidem repudiandae? Id magni, repudiandae doloribus quod officiis esse laborum quia in.
    Modi, aut vero. Autem harum corrupti, quibusdam voluptatibus voluptate culpa sint tempora. Suscipit, magnam omnis. Nemo ab praesentium voluptatem voluptate obcaecati! Perspiciatis, eum odit laudantium adipisci hic alias voluptates? Sint?
    Voluptate rerum ipsa possimus laudantium iste repellendus. Ipsum, nostrum magnam quam dolor eligendi corporis sequi dolore commodi voluptate veniam nemo in repudiandae, sunt, tempora provident animi amet placeat voluptatem est.
    Neque iure ipsum voluptatum deserunt deleniti expedita fuga laboriosam. Labore dolorum incidunt illo ipsum? Nam, non totam earum perferendis pariatur optio praesentium, qui aperiam, consectetur molestias voluptates et in laudantium?
    Debitis nostrum maiores dolorum perferendis accusantium autem quas libero recusandae voluptate. Iste, nulla sequi. Id tempore rerum sed quasi nihil iste provident voluptatem quibusdam perspiciatis ipsam! Quae dolores soluta eius?
    Fugiat, corrupti ducimus laborum consectetur ullam quasi et natus consequatur voluptatibus. Veritatis amet expedita minima quisquam alias quo enim, beatae id soluta, quis dicta placeat voluptatibus. Similique perspiciatis voluptates optio.
    Fuga, distinctio voluptatem at facere minima dolorum eveniet eaque illo alias cum debitis ducimus beatae atque commodi deserunt doloremque, eum magnam laboriosam accusamus? Laborum iste nisi deserunt vitae eius corrupti.
    Ducimus, amet nihil. Quibusdam aliquid excepturi incidunt magni totam. Modi quasi sequi quis hic. Aut quasi libero mollitia ratione a! Expedita amet quos in, tempore velit a vel cum architecto!
    Assumenda dolores, vero non incidunt alias pariatur fuga doloremque autem ut explicabo! Vero ab adipisci perspiciatis cum cupiditate, asperiores facilis excepturi officiis dolor sit quia laborum illum impedit eaque tempora.
    Facere eveniet praesentium id rerum aliquam ex iusto iste expedita asperiores dicta. Sequi corporis atque nam! Quasi dolorum assumenda, ea nesciunt in, porro nostrum iusto deleniti sit magnam corporis laborum.
    Consectetur, optio ipsa placeat error aperiam iusto animi odio laboriosam laudantium beatae voluptate! Aliquid mollitia perspiciatis, quo consequatur voluptate voluptas! Numquam provident doloribus maiores recusandae nam magnam explicabo, necessitatibus optio?
    Vel, officiis. Eius, repudiandae accusantium, ipsam amet omnis natus magnam laborum deserunt saepe cumque quam earum ducimus recusandae iste quae eligendi expedita exercitationem dolorum sunt ad pariatur possimus beatae. Perspiciatis.
    Provident laborum corporis dolorem esse eaque eveniet nulla dolorum illo a in commodi et facilis libero sint vel, nemo at eius fugit harum fugiat, reiciendis dolores! Labore tempore possimus nostrum.
    Repellendus dolore adipisci, similique ipsam quisquam at itaque enim maiores expedita molestiae totam voluptas beatae esse cum corporis laborum quas nam reiciendis necessitatibus earum explicabo reprehenderit ipsum. Ex, totam corrupti!
    Similique nemo vitae quia nam quidem? Reiciendis eius nemo illum ex tenetur ullam in voluptatibus odio, deserunt sapiente repellat delectus unde error atque, veniam consectetur perspiciatis illo repellendus assumenda facere.
    Facere dolorum ducimus odit eligendi sunt nemo. Sed odit nostrum voluptates dicta dignissimos quia velit quam corporis nemo, sunt maiores beatae. Nam magnam error qui. Alias deleniti in eum eveniet?
    Deleniti eius, quas eos qui delectus similique cumque dolore magnam doloremque adipisci velit nostrum quaerat facilis asperiores vero alias soluta reprehenderit ea tempora nisi itaque mollitia inventore in exercitationem? Quae.
    Illo fugiat nihil quisquam ipsa exercitationem amet error quidem ullam laboriosam ut deleniti, eum pariatur sed laudantium esse quam officiis! Magnam ratione porro, dolore excepturi sint ea cum nemo perferendis?
    Dolores necessitatibus, repellendus voluptas iusto saepe magni nemo optio tempore voluptate, provident ducimus minima nobis adipisci laboriosam doloremque corporis unde quo reiciendis sint quos, sit eius inventore? Est, aspernatur beatae.
    Illum quos, nihil explicabo cumque labore laboriosam dolores voluptate ea asperiores doloremque doloribus cum fuga tempora itaque harum necessitatibus quo qui repudiandae natus fugit. Molestias facilis error ducimus fugiat incidunt.
    Quod dolore minus fugit vel eum. Asperiores earum provident tempora impedit, laudantium temporibus nisi exercitationem voluptates incidunt mollitia delectus totam soluta quidem numquam suscipit cumque optio odio vitae neque at.
    Nemo culpa soluta quam doloribus iste modi! Fuga aliquam amet blanditiis quis deleniti, aut ut maiores ullam cupiditate eos quos minima nemo molestias et, veritatis repellat explicabo voluptas quas mollitia.
    Odit amet iusto veritatis? Mollitia ipsam natus amet enim quia, ab distinctio! Mollitia alias earum ab quas animi odit, molestiae perferendis reprehenderit inventore nulla aut voluptatum. Ipsa debitis enim error?
    Inventore porro cumque, odit sit mollitia placeat fugiat sed deleniti alias necessitatibus nulla dicta qui repudiandae beatae aspernatur voluptatum, dolores aut nostrum. Sequi aliquid, libero nostrum ea mollitia necessitatibus unde.
    Atque magnam repellat nobis reiciendis voluptate illum dolor delectus iste, impedit laborum tempore ullam voluptas distinctio assumenda culpa repudiandae vitae nihil, cupiditate illo optio dolorem nulla dicta voluptatum. Inventore, architecto.
    Sed dolorem quaerat animi ipsam suscipit officia, fugiat provident, ut aliquid adipisci modi deserunt nobis rerum voluptates inventore, nulla recusandae similique dolore. Nemo sunt ex necessitatibus pariatur, repudiandae blanditiis eligendi.
    Soluta consectetur voluptatum ea perspiciatis libero excepturi eligendi recusandae veniam quisquam saepe eum iste velit atque est incidunt exercitationem, illum eaque sit architecto? Vero, obcaecati assumenda beatae accusamus quis pariatur!
    Reiciendis minus repudiandae consequuntur similique natus sint sapiente possimus sequi culpa nam, maiores iure eum facilis labore dicta iusto. Non quibusdam molestias magni alias, assumenda quae nemo voluptatem reiciendis aut?
    Eligendi ut architecto itaque. Blanditiis nam eum enim fuga nisi dignissimos, iste quasi accusamus inventore! Vel eum quibusdam quam, odit necessitatibus repellat, deleniti iure a inventore, aut esse voluptatum sapiente.
    Ad non deserunt doloribus tempore quasi, repudiandae provident saepe odit, architecto tenetur repellat similique consectetur! Eaque dignissimos expedita quaerat perspiciatis exercitationem, error incidunt quo. Aliquid ipsum aliquam ratione quos ea.
    Magnam, repellendus maiores optio doloremque provident id voluptate facilis sit natus rem! Sed dolorum earum, quos at repudiandae dolorem eius corporis ut, porro consectetur similique sit, optio vitae. Quia, commodi?
    Architecto dolorem debitis alias molestiae doloribus sit placeat minus ullam veritatis quasi esse iure, aut voluptate? Sequi repellat quibusdam temporibus itaque, officiis blanditiis distinctio veritatis? Assumenda animi odio error totam.
    Fuga corrupti obcaecati error consectetur libero dolorem ex, mollitia reiciendis natus? Nemo error hic vel libero voluptatibus, voluptate, illo quo perspiciatis magnam nobis illum velit saepe? Exercitationem doloribus itaque iusto!
    Reiciendis excepturi ipsa a accusamus aut numquam unde nemo ducimus laborum earum itaque vel fugit asperiores magnam, voluptas sint non reprehenderit quam, cupiditate ullam nostrum! Accusamus ducimus quas nihil debitis?
    Dolore impedit officia vitae sed assumenda nihil doloribus architecto, soluta accusantium! Impedit ipsam cupiditate at nihil, ea rem esse explicabo accusamus exercitationem officia sint est, omnis, maxime veniam vel porro!
    Harum quisquam ipsa totam atque quos, iste delectus nemo suscipit odit eveniet obcaecati tenetur laudantium repellat ab facilis, quasi explicabo recusandae ex temporibus a dicta. Assumenda vero alias odio voluptatibus?
    Suscipit, illo tempore facilis, omnis dignissimos ipsa autem mollitia rerum doloribus libero blanditiis odit qui ipsam voluptates quo sunt, ab ullam natus voluptas quisquam reiciendis nam dolore optio. Maiores, eligendi.
    Ipsam illo voluptates quia quod eveniet? Officiis eius ullam sint quod molestias, placeat minus optio cumque quis! Facilis aut nobis modi, fugit ab error magni ipsam ipsa voluptates nam maxime?
    Ut rerum, excepturi quidem expedita, sint voluptatibus placeat amet voluptates quia illum soluta est ipsum hic id, omnis quo. Ducimus nulla cum magnam vero veritatis eveniet iusto doloremque voluptate reiciendis.
    Assumenda officia aliquid architecto explicabo amet odio voluptates perferendis nisi, officiis magnam, reprehenderit voluptas illum saepe provident natus et vel numquam error laborum ipsa eaque molestiae? Cupiditate, veritatis. Autem, ex?
    Accusamus earum expedita sunt fugiat, ut hic ullam perspiciatis ratione voluptates. Omnis voluptates commodi dolorem quod animi, sequi voluptatem asperiores distinctio dolorum maiores? Maiores laborum enim quia aperiam quo animi.
    Officia harum repudiandae aliquid, unde, sequi reprehenderit dignissimos odio id minima eaque ad nihil molestiae hic. Illum earum nesciunt accusamus, esse deserunt, odio exercitationem nemo atque, explicabo quam iure in.
    Repudiandae voluptatem odio corrupti dignissimos laudantium, minus quia vero quasi perspiciatis eos earum est rerum ducimus esse ipsa atque amet quas voluptatibus ad! Beatae non ipsum ab tempore doloribus totam.
    Ipsam temporibus quo veritatis laudantium voluptas modi adipisci quaerat aspernatur, omnis illum molestiae fugit nam quam dolorem molestias nesciunt dolor asperiores. Ut voluptatum magnam adipisci blanditiis quia odio ducimus maxime!
    Voluptatum provident rem, est reprehenderit aliquid necessitatibus maiores voluptatibus similique iste nam, optio neque voluptate perferendis dicta cumque hic architecto error sapiente dolorem? Cumque, blanditiis. A alias deleniti odit ad.
    Recusandae, quae nostrum sint quaerat sed voluptatum dolorem distinctio excepturi omnis laudantium nulla, molestias quis eligendi laborum modi sit, laboriosam saepe accusamus ad non. Sapiente beatae rerum quasi necessitatibus officiis?
    Nam enim minima vero? Suscipit similique neque odit inventore, atque autem? Quidem vero odit in, neque, eum sequi possimus modi tempore nam ullam blanditiis cupiditate corporis nemo? Eum, ipsa dolor.
    Quia iusto molestiae dolore ullam? Qui dolore facere, nihil sint architecto sunt quidem odio eveniet, atque ratione vel! Praesentium id quisquam vel. Excepturi dignissimos optio autem molestias. Expedita, distinctio nulla!
    Aperiam nostrum officiis, animi eligendi maiores cumque aliquid dicta enim eveniet deserunt consequatur beatae praesentium deleniti, ipsa sint perspiciatis dolores incidunt sunt recusandae sed! Provident ad suscipit alias aperiam molestiae?
    Explicabo quisquam perferendis cum quaerat praesentium asperiores unde, officiis inventore dolorem dolor eos tempore ea similique quasi expedita aspernatur, fugit molestiae itaque earum architecto! Reprehenderit dolore corrupti enim asperiores rerum?
    Fugit deleniti recusandae nisi provident nemo obcaecati officiis, voluptas porro iste, error assumenda dolorum illum molestiae totam eos odio repudiandae blanditiis rem veniam cumque. Sit, ab natus. Quaerat, minus neque!
    Exercitationem saepe quae voluptas, ad porro reprehenderit odio. Ut dolor facilis expedita dignissimos, beatae necessitatibus tempore tempora rerum voluptatum, earum minus aliquid possimus laboriosam cum, id ducimus provident obcaecati at.
    Numquam quae autem ipsam, mollitia vitae quisquam ratione porro debitis obcaecati. Dicta, fugiat eligendi. Sapiente recusandae, amet magnam, reprehenderit ducimus rerum nobis excepturi laudantium temporibus quis officia veniam a laboriosam.
    Necessitatibus asperiores nemo accusamus earum iusto et, suscipit deleniti architecto hic assumenda, dolor itaque commodi quidem illum doloremque. Amet assumenda, odio exercitationem ad saepe ipsam recusandae commodi alias inventore hic!
    Adipisci exercitationem perspiciatis tenetur nihil repudiandae necessitatibus veritatis incidunt repellat nesciunt provident unde illo, beatae error distinctio earum rem excepturi nisi qui? Ipsum temporibus suscipit facere, dolorum molestias eaque consequatur!
    Possimus officia dolorum tempora, architecto aut adipisci temporibus veritatis soluta quisquam laboriosam voluptates, nesciunt numquam laborum deleniti nisi totam magni quis ratione! Totam laboriosam magni pariatur iste modi iure qui.
    Impedit, et consectetur dolore, est tenetur eligendi tempore nihil libero ad dolores recusandae? Nisi, quaerat accusamus! Rerum explicabo nisi inventore corporis ipsum dolor ad ut perspiciatis, ipsa distinctio nesciunt voluptatum.
    Omnis ex, aliquid officia ipsam impedit molestiae a expedita, ratione dolores, soluta ad at quo enim quis rem quasi laudantium deleniti doloremque obcaecati sed fugit dolore? Distinctio minus adipisci iure!
    Saepe, laborum facilis? Et ipsum quo in veniam quae voluptatibus ut repellendus tenetur illum iste? Hic repellat corrupti qui, corporis molestiae harum magni adipisci alias quam laborum, pariatur soluta ipsum!
    Debitis sapiente dicta exercitationem qui. Exercitationem a id, hic commodi vero obcaecati laborum in dignissimos velit molestiae quaerat maxime odio praesentium consequatur soluta doloremque officiis unde dolores dolorum nobis porro!
    Laborum, nam molestias similique illum dolorum nihil quasi voluptates excepturi illo dignissimos consequuntur, dolorem quam deserunt sunt autem rem enim reprehenderit totam. Placeat asperiores, nostrum vitae eum ratione beatae voluptas.
    Nostrum exercitationem tempore odio minus nam, soluta accusantium repellat itaque, nisi et eveniet, laborum debitis aliquam dolore sapiente dolores corporis provident iure consequatur pariatur. Ex velit totam quasi magnam tempore.
    Laudantium quisquam assumenda dicta minima repellat! Perferendis, blanditiis? Animi quam distinctio iste, soluta, provident odio accusamus est placeat ratione odit assumenda suscipit. Repellat, placeat similique corporis natus officiis tempora dolorem?
    Unde quaerat earum vel cum, impedit cupiditate sapiente magnam corporis culpa at tempora optio eligendi ex ab est quo iure id amet a, harum qui quisquam aut! Voluptatum, doloremque soluta!
    Iure iusto a harum minus! At veniam in obcaecati voluptas porro cupiditate, eligendi explicabo enim totam ex, quod facere autem sit omnis, eveniet voluptatibus quasi quidem doloribus suscipit ipsam odio!
    Officiis reiciendis dicta excepturi hic maiores officia optio deserunt ad necessitatibus vitae voluptas dolores culpa sequi harum, animi placeat at dolore error omnis voluptates. Voluptas ut adipisci consequuntur aspernatur ipsum.
    Nemo quam sunt incidunt voluptatem ratione perspiciatis temporibus minus in quod neque, aspernatur similique velit nam officia id unde? Distinctio, ut. Corporis distinctio ut officiis rem animi illum obcaecati veritatis?
    Beatae, in nobis architecto laboriosam perferendis vel accusantium consectetur voluptas necessitatibus itaque autem natus dicta provident adipisci repellendus laudantium expedita doloremque ea ducimus voluptatem iste! Eius nobis et inventore alias!
    Tempora ducimus rerum odio assumenda aspernatur. Temporibus placeat dolor beatae nisi quia voluptas nihil eveniet tenetur error, mollitia repellat quaerat eligendi totam, facilis sunt. Nam voluptas vel quos cumque molestiae.
    Aut, nulla nihil nemo unde saepe voluptate quaerat vero. Vero qui consectetur dolores quidem sequi officia, corporis dignissimos incidunt. Placeat facilis error eveniet ab quo incidunt quisquam impedit laudantium autem!
    Quaerat facilis molestias fuga aspernatur blanditiis, asperiores veritatis praesentium modi, hic tempore repellendus culpa. Odit aliquid, a libero soluta unde id quae, nostrum incidunt harum maxime tempore fugiat! Necessitatibus, modi.
    Quae, odio consequatur? Sed magnam exercitationem qui illo velit asperiores similique odit optio, modi, et tempore harum mollitia iusto, fugit facere obcaecati voluptas tempora consequuntur illum ab eum reprehenderit quidem.
    Recusandae vero tenetur odit officia non dolorem repudiandae animi nostrum voluptatum dolorum sint eligendi molestiae, reiciendis sit deleniti doloribus atque laudantium cupiditate sequi id nobis architecto consequatur mollitia eius. Qui.
    Maiores nisi reiciendis repellat placeat eius blanditiis molestias officia iste, assumenda consectetur perferendis recusandae laudantium sequi repudiandae quidem eligendi totam vero pariatur culpa quo doloribus! Possimus quas ea non doloribus!
    Velit veritatis molestias officiis, eum dolorum animi quidem culpa sapiente. Ipsam velit consectetur quae impedit, quis soluta eligendi atque et vitae obcaecati nulla nostrum quia consequatur accusantium omnis? Repellendus, repudiandae.
    Iure sed magni veniam doloremque mollitia quae sunt sequi quibusdam provident aliquid quaerat adipisci quas quam, at illo distinctio consectetur tempore exercitationem! Voluptates esse quis sed doloribus quo accusantium ad!
    Dolores inventore incidunt ducimus at deserunt dignissimos, ut laudantium magni iusto molestias. Delectus mollitia error vitae totam corporis odit tenetur nostrum similique libero quam neque laborum, pariatur vero necessitatibus molestiae.
    Qui tempora voluptatibus quaerat repellat mollitia autem blanditiis maiores nihil ipsum delectus modi labore doloribus ratione, hic quia voluptates quo illo saepe ad numquam illum debitis commodi? Quasi, aperiam similique!
    Sequi praesentium laudantium eos soluta, dolorem nostrum, eaque magni sit enim ipsa ratione. Doloribus dolor harum, facere totam ipsa quia atque id iure reiciendis sunt, distinctio neque soluta incidunt aperiam.
    Doloribus obcaecati qui, velit esse et labore pariatur! Ea necessitatibus temporibus similique accusamus officia molestiae id voluptatibus quibusdam vero veritatis labore, doloribus nam saepe cumque iure nulla. Dignissimos, amet eaque.
    Vel tenetur sed, quia et necessitatibus cum. Est, quisquam eaque cupiditate aliquam dignissimos similique cum ducimus saepe consequatur cumque nulla nostrum, doloribus magnam! Alias, neque suscipit quod minus sed quia.
    Consectetur, perferendis cum. Delectus reprehenderit consequatur asperiores harum eveniet nostrum, eum quas repellat exercitationem dolorum repellendus ad neque odit voluptatem deleniti sit temporibus commodi quis cupiditate quisquam pariatur nisi blanditiis.
    Minus voluptas minima, earum repellat tempora, quod reprehenderit, deserunt maiores accusamus non magni ut pariatur enim quam atque laboriosam sapiente a voluptatum voluptate. Adipisci asperiores voluptatum aliquid, quas rem tempore?
    Accusantium, animi ullam, iusto illo corporis necessitatibus iste officiis rem quasi dolorem saepe repudiandae laborum blanditiis rerum nisi perspiciatis ratione ex dolor voluptate quis! Consequatur autem vel facere ad eaque!
    Excepturi adipisci neque exercitationem ducimus, aliquid, voluptatum mollitia, vero accusamus optio maxime nam ipsa perferendis veniam amet? Repellat harum assumenda incidunt beatae quis praesentium nihil, blanditiis nisi ea temporibus eum!
    Excepturi in eius tempora, exercitationem officia sit adipisci, laudantium atque quibusdam veritatis hic consectetur quidem nisi reiciendis assumenda illo voluptatum, alias laborum at nihil nesciunt quia repellendus recusandae? Similique, placeat!
    Consequatur quis quae repudiandae iure id incidunt laborum, ipsum nulla hic cupiditate quod aspernatur a, nisi sequi blanditiis harum quo, obcaecati sunt nesciunt dicta. Iste, non. Cupiditate molestiae nisi aliquam?
    Et atque eos cum nobis ex ratione! Iste, non. Commodi quasi modi consequuntur cum nulla optio quaerat sequi excepturi a? Perferendis nemo dolor quo at. Libero blanditiis esse possimus ex!
    Temporibus eaque dolore, maxime expedita porro assumenda, commodi numquam aliquam harum corporis, consequatur omnis tempora? Sunt, at. Nobis eius eaque ex adipisci ea sunt eos ad quos dolor. Fugiat, aut.
    Maiores tempora ad numquam eum nulla eveniet voluptatum est cupiditate odio, inventore quo repudiandae maxime officia eligendi pariatur, ratione dolore reiciendis dicta necessitatibus commodi? Officia, molestias. Veniam adipisci dolor ipsa!
    Vitae odio quae tempora architecto ad sequi dolores soluta similique repellendus ea debitis velit cumque quo beatae hic eius maiores exercitationem, aliquam, ratione necessitatibus! Amet quos magni mollitia sed facere!
    Expedita ratione vel placeat amet perferendis harum, illo, velit minima natus impedit ullam corrupti ab temporibus exercitationem odit. Nam, facere sequi distinctio magni quo delectus architecto ratione temporibus non unde.
    Eos aliquid officiis culpa nobis veritatis nam amet iusto necessitatibus labore distinctio aliquam unde eius consectetur id, obcaecati velit libero recusandae quod! Veniam ex consequatur voluptatibus ipsam excepturi nostrum eligendi!
    Molestias temporibus eos, beatae sunt aperiam rerum laudantium totam ullam consequatur quisquam repellat asperiores ab debitis, nemo impedit et porro recusandae deserunt quos harum libero voluptates quam voluptate! Impedit, obcaecati?</p>
    </>
  )
}

export default Inventario